name: Update Wiki

on:
  push:
    paths:
      - '_wiki/**'
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        
      - name: Update wiki
        uses: actions/setup-node@v2
        with:
          node-version: 16
        run: ./_update_wiki.sh 
        shell: bash
        env:       
          WIKI_DIR: _wiki
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
