name: Update Wiki

on:
  push:
    paths:
      - '_wiki/**'
    branches:
      - main
permissions:
  contents: write
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update wiki
        run: ./_update_wiki.sh 
        shell: bash
        env:       
          WIKI_DIR: _wiki
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
